name: Action-GitHub

on:
  push:
    branches:
      - main
jobs:
  run-robot-scripts:
    runs-on: windows-latest
    env:
      working-directory: ./
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Execute Scripts
        run: |
          pip install webdriver-manager
          pip install robotframework
          pip install robotframework-appiumlibrary
          pip install robotframework-seleniumlibrary
          pip install robotframework-jsonlibrary
          pip install robotframework-requests
          python Tests/name.py
          robot Tests/Web_Login_Test.robot
