name: Action-GitHub

on:
  push:
    branches:
      - main
jobs:
  robot_tests:
    runs-on: windows-latest
    env:
      working-directory: ./
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Create folder for reports
        run: mkdir Reports
      - name: Install Requirements
        run: |
          pip install webdriver-manager
          pip install robotframework
          pip install robotframework-appiumlibrary
          pip install robotframework-seleniumlibrary
          pip install robotframework-jsonlibrary
          pip install robotframework-requests
      - name: Deploy Started Notification
        uses: mikesprague/teams-incoming-webhook-action@v1
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          deploy-card: true
          title: 'Test Started'
          color: 'info'
      - name: Execute Robot Tests
        run: |
          robot -d Report Tests
      - name: Upload reports
        uses: actions/upload-artifact@v3.1.1
        if: always()
        with:
          name: Report
          path: ${{ github.workspace }}/Report
      - name: Success Notification
        if: ${{ success() }}
        uses: mikesprague/teams-incoming-webhook-action@v1
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          deploy-card: true
          title: 'Test Passed'
          color: 'success'
      - name: Failure Notification
        if: ${{ failure() }}
        uses: mikesprague/teams-incoming-webhook-action@v1
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          deploy-card: true
          title: 'Test Failed'
          color: 'failure'
      - name: Cancelled Notification
        if: ${{ cancelled() }}
        uses: mikesprague/teams-incoming-webhook-action@v1
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          deploy-card: true
          title: 'Test Cancelled'
          color: 'warning'

  report:
    if: always()
    needs: [robot_tests]
    runs-on: windows-latest
    steps:
      - name: Repo Checkout
        uses: actions/download-artifact@v3.0.1
        with:
          name: Report

